<div style="width: 1440px; height: 1024px; position: relative; background: white">
    <div style="width: 807px; height: 361px; left: 0px; top: 0px; position: absolute; background: #FF2C2C"></div>
    <div style="width: 861px; height: 115px; left: 0px; top: 94px; position: absolute; text-align: center; color: white; font-size: 132px; font-family: Inter; font-style: italic; font-weight: 800; line-height: 132px; word-wrap: break-word">VEX V5<br/>Robotics</div>
    <div style="width: 793px; height: 609px; left: 17px; top: 394px; position: absolute; text-align: center; color: black; font-size: 27px; font-family: Inter; font-style: italic; font-weight: 800; line-height: 27px; word-wrap: break-word">VEX V5 Robotics is a cutting-edge STEM platform that allows students to design, build, and program robots for both educational and competitive purposes. Each year, teams tackle unique challenges, competing in tasks like scoring objects, manipulating game elements, and navigating autonomous and driver-controlled periods to earn points. Recent games, such as Spin Up and Over Under, emphasize strategic planning and teamwork.<br/>The process involves designing robots with durable VEX hardware, building them using modular components, and programming with VEX code in Python or block coding. Students integrate sensors and motors to optimize performance, combining creativity, engineering, and coding skills to succeed in competitions and develop critical STEM expertise.</div>
    <div style="width: 313px; height: 361px; left: 818px; top: 320px; position: absolute; background: #2CE266"></div>
    <div style="width: 313px; height: 361px; left: 1125px; top: 6px; position: absolute; background: #2EE5E8"></div>
    <div style="width: 313px; height: 361px; left: 1120px; top: 627px; position: absolute; background: #FF1818"></div>
    <div style="width: 237px; height: 51px; left: 861px; top: 335px; position: absolute; text-align: center; color: #202020; font-size: 96px; font-family: Inspiration; font-weight: 400; line-height: 96px; word-wrap: break-word">Build</div>
    <div style="width: 377px; height: 57px; left: 1092px; top: 33px; position: absolute; text-align: center; color: #202020; font-size: 96px; font-family: Inspiration; font-weight: 400; line-height: 96px; word-wrap: break-word">Design</div>
    <div style="width: 237px; height: 51px; left: 1163px; top: 644px; position: absolute; text-align: center; color: white; font-size: 96px; font-family: Inspiration; font-weight: 400; line-height: 96px; word-wrap: break-word">Code</div>
    <div style="width: 290px; height: 221px; left: 828px; top: 440px; position: absolute; text-align: center; color: #121111; font-size: 22px; font-family: Inter; font-style: italic; font-weight: 800; line-height: 22px; word-wrap: break-word">Using VEX V5 components, teams construct robots with modular parts like beams, gears, and motors. Prototyping and iterative testing refine the robot's functionality, ensuring durability and precision.</div>
    <div style="width: 290px; height: 221px; left: 1139px; top: 117px; position: absolute; text-align: center; color: #121111; font-size: 22px; font-family: Inter; font-style: italic; font-weight: 800; line-height: 22px; word-wrap: break-word">Using VEX V5 components, teams construct robots with modular parts like beams, gears, and motors. Prototyping and iterative testing refine the robot's functionality, ensuring durability and precision.</div>
    <div style="width: 290px; height: 221px; left: 1136px; top: 744px; position: absolute; text-align: center; color: #FDECEC; font-size: 22px; font-family: Inter; font-style: italic; font-weight: 800; line-height: 22px; word-wrap: break-word">Programming involves using VEXcode with Python or block coding to control the robot's behavior. Teams write autonomous routines, configure driver controls, and integrate sensors for accurate and responsive performance.</div>
  </div>